---
kind: pipeline
trigger:
  event:
    - cron
    - push
    - tag
  branch:
    - master

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: cenk1cenk2/simple-mail-forwarder
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tag:
        - latest
    when:
      event:
        - push
      branch:
        - master

image_pull_secrets:
  - dockerconfigjson
